spring.application.name=huerto-api

# ============================
#  ORACLE CLOUD CONNECTION
# ============================

spring.datasource.url=jdbc:oracle:thin:@qdi2qhy86mi2lln7_high?TNS_ADMIN=D:\GitHub\CASO-HUERTOHOGAR-REACT-BACKEND\src\main\resources\Wallet_QDI2QHY86MI2LLN7
spring.datasource.username=ADMIN        # cambia esto
spring.datasource.password=Huerto-Hogar25    # cambia esto
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ============================
#  JPA / HIBERNATE
# ============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# ============================
#  SECURITY / JWT
# ============================

spring.main.allow-bean-definition-overriding=true

# ============================
#  SERVER
# ============================

server.port=8080
