spring.datasource.url=jdbc:oracle:thin:@qdi2qhy86mi2lln7_high?TNS_ADMIN=d:/GitHub/CASO-HUERTOHOGAR-REACT-BACKEND/src/main/resources/Wallet_QDI2QHY86MI2LLN7
spring.datasource.username=ADMIN  
spring.datasource.password=Huerto-Hogar25

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.main.allow-bean-definition-overriding=true

server.port=8080
