package com.huertohogar.huerto_api.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(1)
public class DataInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public DataInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {

        // 1) Borrar tablas si existen (hijo -> padre para no romper FKs)
        dropTableIfExists("PRODUCTO_RECETA");
        dropTableIfExists("PRODUCTO");
        dropTableIfExists("CATEGORIA");
        dropTableIfExists("USUARIO");
        dropTableIfExists("BLOG");

        // 2) Crear tablas
        crearTablaUsuario();
        crearTablaCategoria();
        crearTablaProducto();
        crearTablaProductoReceta();
        crearTablaBlog();

        // 3) Poblar datos
        poblarUsuarios();
        poblarCategorias();
        poblarProductos();
        poblarProductoRecetas();
        poblarBlogs();
    }

    // -------------------------------------------------------------------------
    // HELPERS DROP
    // -------------------------------------------------------------------------
    private void dropTableIfExists(String tableName) {
        String sql = """
                BEGIN
                  EXECUTE IMMEDIATE 'DROP TABLE %s CASCADE CONSTRAINTS';
                EXCEPTION
                  WHEN OTHERS THEN
                    IF SQLCODE != -942 THEN
                      RAISE;
                    END IF;
                END;
                """.formatted(tableName);
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception e) {
            // ignoramos el error para no bloquear el arranque
        }
    }

    // -------------------------------------------------------------------------
    // CREACIÓN DE TABLAS
    // -------------------------------------------------------------------------
    private void crearTablaUsuario() {
        jdbcTemplate.execute("""
                CREATE TABLE USUARIO (
                    ID               NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                    USERNAME         VARCHAR2(50 CHAR)  NOT NULL,
                    PASSWORD         VARCHAR2(100 CHAR) NOT NULL,
                    ROLE             VARCHAR2(20 CHAR)  NOT NULL,
                    NOMBRE           VARCHAR2(100 CHAR),
                    APELLIDO         VARCHAR2(100 CHAR),
                    RUN              VARCHAR2(20 CHAR),
                    FECHA_NACIMIENTO VARCHAR2(20 CHAR),
                    REGION           VARCHAR2(100 CHAR),
                    COMUNA           VARCHAR2(100 CHAR),
                    DIRECCION        VARCHAR2(200 CHAR),
                    EMAIL            VARCHAR2(150 CHAR) NOT NULL,
                    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
                )
                """);

        jdbcTemplate.execute("""
                CREATE UNIQUE INDEX UK_USUARIO_USERNAME ON USUARIO (USERNAME)
                """);
        jdbcTemplate.execute("""
                CREATE UNIQUE INDEX UK_USUARIO_EMAIL ON USUARIO (EMAIL)
                """);
    }

    // NUEVA TABLA CATEGORIA
    private void crearTablaCategoria() {
        jdbcTemplate.execute("""
                CREATE TABLE CATEGORIA (
                    ID     NUMBER(10)          PRIMARY KEY,
                    NOMBRE VARCHAR2(100 CHAR)  NOT NULL,
                    SLUG   VARCHAR2(100 CHAR)  NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE UNIQUE INDEX UK_CATEGORIA_SLUG ON CATEGORIA (SLUG)
                """);
    }

    private void crearTablaProducto() {
        jdbcTemplate.execute("""
                CREATE TABLE PRODUCTO (
                    ID                    NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY,
                    CODIGO                VARCHAR2(10 CHAR) NOT NULL,
                    NOMBRE                VARCHAR2(100 CHAR) NOT NULL,
                    PRECIO                NUMBER(10,2)      NOT NULL,
                    STOCK                 NUMBER(10)        NOT NULL,
                    DESCRIPCION_CORTA     VARCHAR2(255 CHAR),
                    DESCRIPCION_LARGA     VARCHAR2(2000 CHAR),
                    IMAGEN                VARCHAR2(255 CHAR),
                    CATEGORY_ID           NUMBER(10),
                    ORIGEN                VARCHAR2(100 CHAR),
                    PRACTICAS_SOSTENIBLES VARCHAR2(255 CHAR),
                    PRIMARY KEY (ID),
                    CONSTRAINT FK_PRODUCTO_CATEGORIA
                      FOREIGN KEY (CATEGORY_ID)
                      REFERENCES CATEGORIA(ID)
                )
                """);

        jdbcTemplate.execute("""
                CREATE UNIQUE INDEX UK_PRODUCTO_CODIGO ON PRODUCTO (CODIGO)
                """);
    }

    private void crearTablaProductoReceta() {
        jdbcTemplate.execute("""
                CREATE TABLE PRODUCTO_RECETA (
                    PRODUCTO_ID  NUMBER(19,0) NOT NULL,
                    RECETA       VARCHAR2(255 CHAR),
                    CONSTRAINT FK_PROD_RECETA_PROD
                      FOREIGN KEY (PRODUCTO_ID)
                      REFERENCES PRODUCTO(ID)
                )
                """);
    }

    private void crearTablaBlog() {
        jdbcTemplate.execute("""
                CREATE TABLE BLOG (
                    ID           NUMBER(19)         PRIMARY KEY,
                    BLOG_ID      VARCHAR2(50 CHAR)  NOT NULL,
                    IMAGEN       VARCHAR2(200 CHAR),
                    ALT          VARCHAR2(150 CHAR),
                    TITULO       VARCHAR2(150 CHAR) NOT NULL,
                    TITULO_MODAL VARCHAR2(200 CHAR),
                    RESUMEN      VARCHAR2(500 CHAR) NOT NULL,
                    INTRO        VARCHAR2(2000 CHAR),
                    CONTENIDO    VARCHAR2(4000 CHAR),
                    OUTRO        VARCHAR2(2000 CHAR)
                )
                """);

        jdbcTemplate.execute("""
                CREATE UNIQUE INDEX UK_BLOG_BLOG_ID ON BLOG (BLOG_ID)
                """);
    }

    // -------------------------------------------------------------------------
    // POBLAR USUARIOS
    // -------------------------------------------------------------------------
    private void poblarUsuarios() {
        // admin / admin123
        jdbcTemplate.update("""
                INSERT INTO USUARIO (
                    USERNAME, PASSWORD, ROLE, NOMBRE, APELLIDO, RUN,
                    FECHA_NACIMIENTO, REGION, COMUNA, DIRECCION, EMAIL
                ) VALUES (
                    'admin',
                    '$2b$12$AqzktPT7IbgfrKtO7AkWx.4FrS3EoHYz3l2FbTpCijW446bVSrVAm',
                    'admin',
                    'Admin',
                    ' ',
                    ' ',
                    NULL,
                    ' ',
                    ' ',
                    ' ',
                    'admin@duoc.cl'
                )
                """);

        // Maria / 1234
        jdbcTemplate.update("""
                INSERT INTO USUARIO (
                    USERNAME, PASSWORD, ROLE, NOMBRE, APELLIDO, RUN,
                    FECHA_NACIMIENTO, REGION, COMUNA, DIRECCION, EMAIL
                ) VALUES (
                    'Maria',
                    '$2b$12$iyxeQdlp2N3oxxNbd1564O.Yl9YydPJmTT3H/cVabFrBegOwJmeWy',
                    'cliente',
                    'Maria',
                    'Florez',
                    '123456789-k',
                    '1990-05-02',
                    'Biobío',
                    'Chillán',
                    '0289-K',
                    'maria@gmail.com'
                )
                """);

        // Pedro / pedro123
        jdbcTemplate.update("""
                INSERT INTO USUARIO (
                    USERNAME, PASSWORD, ROLE, NOMBRE, APELLIDO, RUN,
                    FECHA_NACIMIENTO, REGION, COMUNA, DIRECCION, EMAIL
                ) VALUES (
                    'Pedro',
                    '$2b$12$yhyrB5vtWQ41rrpC5dn13uIcD7wt8T9H/bzv1PRhATTjs9uCRwrka',
                    'vendedor',
                    'Pedro',
                    'Gonzalez',
                    '987654321-k',
                    '1985-08-15',
                    'Biobío',
                    'Chillán',
                    '0289-K',
                    'pedro@profesor.duoc.cl'
                )
                """);
    }

    // -------------------------------------------------------------------------
    // POBLAR CATEGORÍAS
    // -------------------------------------------------------------------------
    private void poblarCategorias() {
        jdbcTemplate.update("""
                INSERT INTO CATEGORIA (ID, NOMBRE, SLUG)
                VALUES (1, 'Frutas Frescas', 'frutas-frescas')
                """);

        jdbcTemplate.update("""
                INSERT INTO CATEGORIA (ID, NOMBRE, SLUG)
                VALUES (2, 'Verduras Orgánicas', 'verduras-organicas')
                """);

        jdbcTemplate.update("""
                INSERT INTO CATEGORIA (ID, NOMBRE, SLUG)
                VALUES (3, 'Productos Orgánicos', 'productos-organicos')
                """);

        jdbcTemplate.update("""
                INSERT INTO CATEGORIA (ID, NOMBRE, SLUG)
                VALUES (4, 'Productos Lácteos', 'productos-lacteos')
                """);
    }

    // -------------------------------------------------------------------------
    // POBLAR PRODUCTOS
    // -------------------------------------------------------------------------
    private void poblarProductos() {

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    1,
                    'FR001',
                    'Kilo de manzanas Fuji',
                    1200, 150,
                    'Manzanas crujientes del Valle del Maule',
                    'Manzanas Fuji crujientes y dulces, cultivadas en el Valle del Maule. Perfectas para meriendas saludables o como ingrediente en postres.',
                    './public/img/img_productos/manzanas-fuji.jpg',
                    1,
                    'Valle del Maule',
                    'Cultivo responsable con bajo uso de pesticidas.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    2,
                    'FR002',
                    'Kilo de naranjas Valencia',
                    1000, 200,
                    'Jugosas y ricas en vitamina C',
                    'Jugosas y ricas en vitamina C, ideales para zumos frescos y refrescantes.',
                    './public/img/img_productos/naranjas-valencia.jpg',
                    1,
                    'Región de Coquimbo',
                    'Cultivo en huertos familiares con riego eficiente.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    3,
                    'FR003',
                    'Kilo de plátanos Cavendish',
                    800, 250,
                    'Plátanos dulces, ricos en potasio',
                    'Plátanos maduros y dulces, perfectos para el desayuno o como snack energético.',
                    './public/img/img_productos/platanos-cavendish.jpg',
                    1,
                    'Zona Central',
                    'Producidos bajo certificación de comercio justo.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    4,
                    'VR001',
                    'Kilo de zanahorias Orgánicas',
                    900, 100,
                    'Cultivadas sin pesticidas en O''Higgins',
                    'Zanahorias crujientes cultivadas sin pesticidas en la Región de O''Higgins.',
                    './public/img/img_productos/zanahorias-organicas.jpg',
                    2,
                    'Región de O''Higgins',
                    'Certificación orgánica, libres de químicos.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    5,
                    'VR002',
                    'Bolsa de 500g espinacas Frescas',
                    700, 80,
                    'Espinacas frescas y nutritivas',
                    'Espinacas frescas y nutritivas, perfectas para ensaladas y batidos verdes.',
                    './public/img/img_productos/espinacas-frescas.jpg',
                    2,
                    'Zona Central',
                    'Cultivo con compost natural y riego eficiente.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    6,
                    'VR003',
                    'Kilo de pimientos Tricolores',
                    1500, 120,
                    'Rojos, amarillos y verdes, ricos en antioxidantes',
                    'Pimientos rojos, amarillos y verdes, ideales para salteados y platos coloridos.',
                    './public/img/img_productos/pimientos-tricolores.jpg',
                    2,
                    'Región de Valparaíso',
                    'Cosecha a mano para reducir impacto ambiental.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    7,
                    'PO001',
                    'Frasco de 500g miel Orgánica',
                    5000, 50,
                    'Miel pura de apicultores locales',
                    'Miel 100% pura, producida por apicultores locales.',
                    './public/img/img_productos/miel-organica.jpg',
                    3,
                    'Zona Central',
                    'Producción apícola responsable y sin químicos.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    8,
                    'PO003',
                    'Quinua Orgánica (500g)',
                    2500, 60,
                    'Grano saludable y nutritivo',
                    'Quinua orgánica, rica en proteínas y libre de gluten.',
                    './public/img/img_productos/quinua-organica.jpg',
                    3,
                    'Región de Los Lagos',
                    'Cultivo andino sostenible con bajo impacto.'
                )
                """);

        jdbcTemplate.update("""
                INSERT INTO PRODUCTO (
                    ID, CODIGO, NOMBRE, PRECIO, STOCK,
                    DESCRIPCION_CORTA, DESCRIPCION_LARGA,
                    IMAGEN, CATEGORY_ID, ORIGEN, PRACTICAS_SOSTENIBLES
                ) VALUES (
                    9,
                    'PL001',
                    'Litro de leche Entera',
                    1200, 90,
                    'Leche fresca de granjas locales',
                    'Leche entera fresca, nutritiva y deliciosa, proveniente de granjas locales.',
                    './public/img/img_productos/leche-entera.jpg',
                    4,
                    'Zona Central',
                    'Producida bajo estándares de bienestar animal.'
                )
                """);
    }

    // -------------------------------------------------------------------------
    // POBLAR PRODUCTO_RECETA
    // -------------------------------------------------------------------------
    private void poblarProductoRecetas() {

        insertarRecetaProd(1L, "Ensalada de manzana y nueces");
        insertarRecetaProd(1L, "Tarta de manzana casera");
        insertarRecetaProd(1L, "Jugo natural de manzana y zanahoria");

        insertarRecetaProd(2L, "Jugo de naranja natural");
        insertarRecetaProd(2L, "Ensalada de cítricos");
        insertarRecetaProd(2L, "Pollo glaseado con naranja");

        insertarRecetaProd(3L, "Batido de plátano");
        insertarRecetaProd(3L, "Pan de plátano");
        insertarRecetaProd(3L, "Helado de plátano casero");

        insertarRecetaProd(4L, "Jugo de zanahoria");
        insertarRecetaProd(4L, "Ensalada rallada");
        insertarRecetaProd(4L, "Crema de zanahoria");

        insertarRecetaProd(5L, "Tortilla de espinaca");
        insertarRecetaProd(5L, "Ensalada de espinaca fresca");
        insertarRecetaProd(5L, "Batido verde");

        insertarRecetaProd(6L, "Salteado de pimientos");
        insertarRecetaProd(6L, "Pimientos rellenos");
        insertarRecetaProd(6L, "Ensalada tricolor");

        insertarRecetaProd(7L, "Té con miel");
        insertarRecetaProd(7L, "Galletas de miel");
        insertarRecetaProd(7L, "Aderezo de miel y mostaza");

        insertarRecetaProd(8L, "Ensalada de quinua");
        insertarRecetaProd(8L, "Quinua con verduras");
        insertarRecetaProd(8L, "Guiso de quinua");

        insertarRecetaProd(9L, "Leche con chocolate");
        insertarRecetaProd(9L, "Budín de pan");
        insertarRecetaProd(9L, "Arroz con leche");
    }

    private void insertarRecetaProd(Long productoId, String receta) {
        jdbcTemplate.update("""
                INSERT INTO PRODUCTO_RECETA (PRODUCTO_ID, RECETA)
                VALUES (?, ?)
                """, productoId, receta);
    }

    // -------------------------------------------------------------------------
    // POBLAR BLOGS
    // -------------------------------------------------------------------------
    private void poblarBlogs() {

        // BLOG 1
        jdbcTemplate.update("""
                INSERT INTO BLOG (
                    ID, BLOG_ID, IMAGEN, ALT, TITULO, TITULO_MODAL,
                    RESUMEN, INTRO, CONTENIDO, OUTRO
                ) VALUES (
                    1,
                    'blogModal1',
                    'img-blog1.webp',
                    'Caso curioso 1',
                    'CASO CURIOSO #1',
                    'Tips para cuidar tu huerto urbano en casa.',
                    'Nuestro equipo comparte consejos simples para cuidar tu huerto urbano con prácticas sostenibles.',
                    'En Huerto Hogar creemos que tener un pequeño huerto en casa no solo embellece tu espacio, sino que también te conecta con la naturaleza y fomenta un estilo de vida más saludable.',
                    'Elige plantas fáciles de mantener, usa recipientes con buen drenaje y procura regar en los horarios de menor calor para aprovechar mejor el agua.',
                    'Cultivar tu propio huerto urbano es más sencillo de lo que parece si eres constante y observas el crecimiento de tus plantas día a día.'
                )
                """);

        // BLOG 2
        jdbcTemplate.update("""
                INSERT INTO BLOG (
                    ID, BLOG_ID, IMAGEN, ALT, TITULO, TITULO_MODAL,
                    RESUMEN, INTRO, CONTENIDO, OUTRO
                ) VALUES (
                    2,
                    'blogModal2',
                    'img-blog2.jpg',
                    'Caso curioso 2',
                    'CASO CURIOSO #2',
                    'Pequeños cambios en tu jardín que ayudan al medio ambiente.',
                    'A veces pensamos que para ayudar al planeta se necesitan grandes acciones, pero tu propio jardín puede marcar la diferencia.',
                    'Si eliges plantas nativas, reduces el uso de químicos y aprovechas mejor el agua de riego, estás creando un espacio más amigable con la biodiversidad.',
                    'También puedes hacer tu propio compost con restos de frutas y verduras para mejorar el suelo y producir menos basura en casa.',
                    'Cada pequeño cambio suma: tu jardín puede convertirse en un refugio verde que aporta bienestar a tu hogar y al entorno.'
                )
                """);
    }
}
